# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-25 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='plot',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(),
        ),
    ]
